[project]
name = "pennylm"
version = "0.1.0"
description = "Training scripts and data notebook for Penny"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=3.6.0",
    "jupyter>=1.1.1",
    "transformers>=4.52.4",
    "trl>=0.18.1",
]
